package br.com.di2win.digitalaccount.common.exception;

public enum ErrorCode {
    CUSTOMER_NOT_FOUND,
    CPF_ALREADY_REGISTERED,
    ACCOUNT_NOT_FOUND,
    ACCOUNT_ALREADY_EXISTS,
    ACCOUNT_BLOCKED,
    ACCOUNT_INACTIVE,
    INSUFFICIENT_FUNDS,
    DAILY_WITHDRAWAL_LIMIT_EXCEEDED,
    CUSTOMER_HAS_POSITIVE_BALANCE,
    INVALID_AMOUNT,
    VALIDATION_ERROR,
    MALFORMED_JSON,
    DATA_INTEGRITY_VIOLATION,
    INTERNAL_ERROR
}
